title: PBB Updates Board
description: PBB Updates Board from DRPS PHCA
url: "https://pbbupdates.drpsphca.com"
baseurl: "/pbb-updates"
theme_name: gen11-arcade

season_id: gen11

plugins: []
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

defaults:
  - scope:
      path: "api"
    values:
      layout: json
